telemetry = false

[run]
silent = true

[install]
minimumReleaseAge = 172800

minimumReleaseAgeExcludes = [
  "@astrojs/check",
  "@astrojs/preact",
  "@kamod-ch/ui",
  "@types/bun",
  "@types/node",
  "astro",
  "bun-types",
  "preact",
  "typescript",
]